name: CI

on:
  push:
    branches: [main]
    paths:
      - "fe/**"
      - ".github/workflows/fe-ci.yaml"
      - "yarn.lock"
  pull_request:
    paths:
      - "fe/**"
      - ".github/workflows/fe-ci.yaml"
      - "yarn.lock"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Setup Yarn Berry
        run: corepack enable
      - name: Install deps
        run: yarn install --immutable
        working-directory: .
      - name: Biome Check
        run: yarn workspace icod2-fe lint .
        working-directory: .
      - name: TypeScript Compile Check
        run: yarn workspace icod2-fe build
        working-directory: .
